title: Widget Service
description: Sorted Widget Service
version: 1.0
termsOfServiceUrl: https://livesorted.com
contact:
    name: sorted
    url: #
    email: support@livesorted.com
license: Copyright Licence
licenseUrl: https://livesorted.com
host_local: localhost:8610
host_dev: widget-dev.livesorted.com
host_prod: widget.livesorted.com